---
- name: 'Converge'
  hosts: 'all'
  become: true
  gather_facts: true
  collections:
    - lacrif.trellix
  roles:
    - role: 'lacrif.trellix.trellix_agent'
      trellix_agent_version: '5.8.5'
    - role: 'lacrif.trellix.trellix_ens_tp'
      trellix_ens_tp_version: '10.7.21'
    - role: 'lacrif.trellix.trellix_esp_kernelmodule'
      trellix_esp_kernelmodule_version: '10.7.21'
    - role: 'lacrif.trellix.trellix_ens_fw'
      trellix_ens_fw_version: '10.7.21'
