---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: 'docker'

platforms:
  - name: 'dk-debian-instance'
    image: 'lacrif/debian-systemd:bookworm'
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    cgroupns_mode: 'host'
    privileged: true
    pre_build_image: true

provisioner:
  name: 'ansible'

verifier:
  name: testinfra

scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
